### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by jonascheng** [trendmicro/serverless-survey-forms#1]
- [ ] Add inline script in Vagrant to provision git and serverless framework
- [ ] Add survey table in s-resources-cf.json
- [ ] Allow Lambda default IAM role to access survey table
- [ ] Add apiResponseTemplate in s-templates.json to handle HTTP status code
- [ ] NPM install aws-sdk and node-uuid in subfolder 'api' for lambda functions
- [ ] Define endpoints to access survey table in SuveyFeedback
- [ ] Implement lambda functions to access survey table
  - [ ] get one survey model
  - [ ] post a new survey model
  - [ ] update a survey model
  - [ ] delete a survey model
  - [ ] list all survey model
- [ ] Define endpoints to access feedback table in SuveyFeedback
  - [ ] get one feedback model
  - [ ] post a new feedback model
  - [ ] update a feedback model
  - [ ] delete a feedback model
  - [ ] list all feedback model
- [ ] Define endpoints to access user table in AuthUser
  - [ ] get one account
  - [ ] post a new account
  - [ ] update an account
  - [ ] delete an account
  - [ ] list all accounts
