### ISSUE TITLE
CI TODO List

### ISSUE THREAD

**Issue by jonascheng** [trendmicro/serverless-survey-forms#2]

**Comment by jonascheng** [comment]
- [ ] NPM install mocha in root folder and write an dummy test case
- [ ] Initial Travis CI and make sure trigger on each submission
- [ ] Prepare test cases for survey 
  - [ ] 
- [ ] Enable ESlint in CI
- [ ] Enable code coverage in CI
